FOOD_101_TO_INGREDIENTS = {
    "apple_pie": ["apples", "sugar", "cinnamon", "flour", "butter", "egg"],
    "baby_back_ribs": ["pork ribs", "barbecue sauce", "spices", "garlic", "onion"],
    "baklava": ["phyllo dough", "honey", "pistachios", "walnuts", "butter", "sugar"],
    "beef_carpaccio": ["beef", "arugula", "lemon", "olive oil", "capers", "parmesan"],
    "beef_tartare": ["beef", "egg yolk", "capers", "onion", "mustard", "parsley"],
    "beignets": ["flour", "egg", "milk", "sugar", "yeast", "powdered sugar"],
    "bibimbap": ["rice", "beef", "vegetables", "egg", "gochujang", "sesame oil"],
    "bread_pudding": ["bread", "milk", "egg", "sugar", "butter", "vanilla"],
    "breakfast_burrito": ["tortilla", "egg", "bacon", "cheese", "potato", "salsa"],
    "bruschetta": ["bread", "tomato", "basil", "garlic", "olive oil", "mozzarella"],
    "caesar_salad": [
        "romaine lettuce",
        "parmesan",
        "croutons",
        "caesar dressing",
        "anchovy",
    ],
    "cannoli": [
        "ricotta cheese",
        "phillo dough",
        "sugar",
        "chocolate chips",
        "candied fruit",
    ],
    "caprese_salad": ["tomato", "mozzarella", "basil", "olive oil", "balsamic vinegar"],
    "carrot_cake": ["carrots", "cream cheese", "sugar", "flour", "egg", "walnuts"],
    "ceviche": ["fish", "lime", "onion", "cilantro", "avocado", "chili"],
    "cheesecake": [
        "cream cheese",
        "graham cracker",
        "sugar",
        "egg",
        "vanilla",
        "sour cream",
    ],
    "cheese_plate": ["cheese", "crackers", "grapes", "fig jam", "almonds", "honey"],
    "chicken_curry": [
        "chicken",
        "curry paste",
        "coconut milk",
        "onion",
        "garlic",
        "ginger",
    ],
    "chicken_quesadilla": [
        "tortilla",
        "chicken",
        "cheese",
        "peppers",
        "onion",
        "sour cream",
    ],
    "chicken_wings": [
        "chicken wings",
        "hot sauce",
        "butter",
        "garlic",
        "flour",
        "blue cheese dip",
    ],
    "chocolate_cake": [
        "flour",
        "sugar",
        "cocoa powder",
        "egg",
        "butter",
        "chocolate frosting",
    ],
    "chocolate_mousse": ["chocolate", "egg", "sugar", "cream", "butter", "vanilla"],
    "churros": [
        "flour",
        "egg",
        "butter",
        "water",
        "sugar",
        "cinnamon",
        "chocolate sauce",
    ],
    "clam_chowder": ["clams", "potato", "cream", "bacon", "onion", "thyme"],
    "club_sandwich": ["bread", "turkey", "bacon", "lettuce", "tomato", "mayonnaise"],
    "crab_cakes": [
        "crab meat",
        "breadcrumbs",
        "egg",
        "mayonnaise",
        "mustard",
        "parsley",
    ],
    "creme_brulee": ["cream", "egg", "sugar", "vanilla", "caramelized sugar"],
    "croque_madame": ["bread", "ham", "cheese", "bechamel sauce", "egg", "butter"],
    "cup_cakes": [
        "flour",
        "sugar",
        "egg",
        "butter",
        "milk",
        "cocoa powder",
        " frosting",
    ],
    "deviled_eggs": ["egg", "mayonnaise", "mustard", "paprika", "pickle", "chives"],
    "donuts": ["flour", "yeast", "sugar", "milk", "egg", "powdered sugar", "jam"],
    "dumplings": ["flour", "pork", "cabbage", "ginger", "garlic", "soy sauce"],
    "edamame": ["edamame beans", "sea salt"],
    "eggs_benedict": ["english muffin", "ham", "poached egg", "hollandaise sauce"],
    "eggs_scrambled": ["egg", "butter", "milk", "chives", "salt", "pepper"],
    "escargots": ["snails", "garlic", "butter", "parsley", "shallot", "white wine"],
    "falafel": [
        "chickpeas",
        "parsley",
        "onion",
        "garlic",
        "cumin",
        "coriander",
        "falafel",
    ],
    "filet_mignon": [
        "beef tenderloin",
        "butter",
        "garlic",
        "thyme",
        "olive oil",
        "salt",
    ],
    "fish_and_chips": [
        "fish",
        "potato",
        "flour",
        "beer batter",
        "tartar sauce",
        "malt vinegar",
    ],
    "foie_gras": ["duck liver", "fig jam", "brioche", "sauternes wine", "truffle"],
    "french_fries": ["potato", "salt", "vegetable oil"],
    "french_onion_soup": [
        "onion",
        "beef broth",
        "gruyere cheese",
        "bread",
        "white wine",
    ],
    "french_toast": ["bread", "egg", "milk", "cinnamon", "butter", "maple syrup"],
    "fried_calamari": [
        "calamari",
        "flour",
        "garlic",
        "lemon",
        "marinara sauce",
        "tartar sauce",
    ],
    "fried_rice": [
        "rice",
        "egg",
        "vegetables",
        "soy sauce",
        "sesame oil",
        "green onion",
    ],
    "frozen_yogurt": ["yogurt", "fruit", "honey", "granola", "chocolate chips"],
    "garlic_bread": ["bread", "garlic", "butter", "parsley", "parmesan"],
    "gnocchi": ["potato", "flour", "egg", "ricotta cheese", "parmesan", "pesto"],
    "grilled_cheese": ["bread", "cheese", "butter"],
    "grilled_salmon": ["salmon", "lemon", "dill", "olive oil", "garlic", "capers"],
    "guacamole": ["avocado", "lime", "onion", "cilantro", "tomato", "jalapeno"],
    "gyoza": ["dumpling wrapper", "pork", "cabbage", "ginger", "garlic", "soy sauce"],
    "hamburger": [
        "beef patty",
        "burger bun",
        "lettuce",
        "tomato",
        "onion",
        "pickle",
        "ketchup",
    ],
    "hot_and_sour_soup": [
        "tofu",
        "mushroom",
        "egg",
        "bamboo shoots",
        "pork",
        "vinegar",
        "chili",
    ],
    "hot_dog": ["hot dog bun", "sausage", "mustard", "ketchup", "onion"],
    "huevos_rancheros": [
        "egg",
        "tortilla",
        "black beans",
        "salsa",
        "cheese",
        "avocado",
    ],
    "hummus": ["chickpeas", "tahini", "lemon", "garlic", "olive oil", "cumin"],
    "ice_cream": ["cream", "milk", "sugar", "egg", "vanilla", "fruit"],
    "lasagna": [
        "pasta",
        "beef",
        "tomato sauce",
        "ricotta cheese",
        "mozzarella",
        "parmesan",
    ],
    "lobster_bisque": ["lobster", "cream", "white wine", "shallot", "tomato", "thyme"],
    "lobster_roll_sandwich": [
        "lobster",
        "mayonnaise",
        "celery",
        "lettuce",
        "hot dog bun",
    ],
    "macaroni_and_cheese": [
        "macaroni",
        "cheese",
        "milk",
        "butter",
        "flour",
        "breadcrumbs",
    ],
    "macarons": ["almond flour", "egg white", "sugar", "food coloring", "filling"],
    "miso_soup": ["miso paste", "tofu", "seaweed", "green onion", "dashi"],
    "mussels": ["mussels", "white wine", "garlic", "shallot", "parsley", "cream"],
    "nachos": [
        "tortilla chips",
        "cheese",
        "jalapeno",
        "black beans",
        "sour cream",
        "guacamole",
    ],
    "omelette": ["egg", "butter", "cheese", "mushroom", "onion", "ham"],
    "onion_rings": ["onion", "flour", "egg", "breadcrumbs", "buttermilk", "ranch dip"],
    "oysters": ["oysters", "lemon", "mignonette sauce", "hot sauce"],
    "pad_thai": [
        "rice noodles",
        "shrimp",
        "bean sprouts",
        "peanuts",
        "lime",
        "fish sauce",
        "egg",
        "tofu",
    ],
    "paella": [
        "rice",
        "saffron",
        "shrimp",
        "mussels",
        "chicken",
        "vegetables",
        "smoked paprika",
    ],
    "pancakes": ["flour", "milk", "egg", "butter", "maple syrup", "blueberries"],
    "panna_cotta": ["cream", "sugar", "vanilla", "gelatin", "strawberry sauce"],
    "peking_duck": ["duck", "pancakes", "scallion", "cucumber", "hoisin sauce"],
    "pho": [
        "rice noodles",
        "beef",
        "beef broth",
        "star anise",
        "basil",
        "lime",
        "bean sprouts",
    ],
    "pizza": ["pizza dough", "tomato sauce", "mozzarella", "basil", "olive oil"],
    "pork_chop": ["pork chop", "butter", "garlic", "rosemary", "thyme", "apple sauce"],
    "poutine": ["fries", "cheese curds", "gravy", "butter"],
    "prime_rib": ["beef rib", "horseradish", "au jus", "roasted vegetables"],
    "pulled_pork_sandwich": [
        "pork shoulder",
        "barbecue sauce",
        "coleslaw",
        "pickle",
        "burger bun",
    ],
    "ramen": [
        "noodles",
        "pork",
        "soft egg",
        "norí",
        "green onion",
        "char siu",
        "garlic",
    ],
    "ravioli": ["pasta", "ricotta cheese", "parmesan", "spinach", "tomato sauce"],
    "red_velvet_cake": [
        "flour",
        "cocoa powder",
        "buttermilk",
        "cream cheese frosting",
        "food coloring",
    ],
    "risotto": [
        "arborio rice",
        "white wine",
        "parmesan",
        "onion",
        "butter",
        "vegetables",
    ],
    "samosa": ["pastry", "potato", "peas", "curry", "ginger", "garlic"],
    "sashimi": ["raw fish", "soy sauce", "wasabi", "ginger"],
    "scallops": ["scallops", "butter", "lemon", "garlic", "white wine", "parsley"],
    "seaweed_salad": [
        "seaweed",
        "sesame oil",
        "rice vinegar",
        "cucumber",
        "sesame seeds",
    ],
    "shrimp_and_grits": ["shrimp", "grits", "bacon", "green onion", "garlic", "butter"],
    "spaghetti_bolognese": [
        "spaghetti",
        "beef",
        "tomato sauce",
        "onion",
        "garlic",
        "parmesan",
    ],
    "spaghetti_carbonara": [
        "spaghetti",
        "guanciale",
        "egg",
        "parmesan",
        "black pepper",
    ],
    "spring_rolls": ["rice paper", "vegetables", "shrimp", "mint", "peanut sauce"],
    "steak": ["beef steak", "butter", "garlic", "rosemary", "olive oil", "salt"],
    "steak_eggplant_parmesan": [
        "eggplant",
        "tomato sauce",
        "mozzarella",
        "parmesan",
        "beef",
    ],
    "sushi": ["sushi rice", "nori", "raw fish", "avocado", "cucumber", "soy sauce"],
    "tacos": [
        "tortilla",
        "beef",
        "lettuce",
        "cheese",
        "salsa",
        "sour cream",
        "guacamole",
    ],
    "takoyaki": [
        "octopus",
        "batter",
        "green onion",
        "pickled ginger",
        "bonito flakes",
        "takoyaki sauce",
    ],
    "tiramisu": [
        "mascarpone cheese",
        "espresso",
        "ladyfingers",
        "cocoa powder",
        "egg",
        "sugar",
    ],
    "tuna_tartare": ["tuna", "avocado", "sesame oil", "soy sauce", "lime", "seaweed"],
    "waffles": ["flour", "milk", "egg", "butter", "yeast", "maple syrup"],
    "wine_calamari": ["calamari", "wine", "garlic", "tomato sauce", "arugula"],
    "zucchini": ["zucchini", "parmesan", "egg", "garlic", "breadcrumbs", "olive oil"],
}
